//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Estructura de datos.rc
//
#define IDD_Login                       101
#define IDD_Especialidades              103
#define IDD_Alta                        105
#define IDD_Menu                        107
#define IDD_AltaEspecialidades          109
#define IDD_EditarEspecialidades        111
#define IDD_RegistroMedico              113
#define IDD_Pacientes                   115
#define IDD_RegistroCitas               117
#define IDD_MostrarCita                 119
#define IDD_ConsultaCita                121
#define IDD_Cancelacion                 123
#define IDD_BuscardorCitasMedico        125
#define IDD_VerCitasDoctor              127
#define IDD_BuscardorCitasSemana        129
#define IDD_BuscadorEspecialidad        131
#define IDD_MostrarPacientes            133
#define IDD_editarPacientes             135
#define IDD_mostrarMedicos              137
#define IDD_edicionMedicos              139
#define IDD_EdicionCItas                141
#define IDB_Login                       1001
#define IDB_Salir                       1002
#define ED_User                         1004
#define ED_Pass                         1005
#define IDB_GuardarUser                 1005
#define IDB_RegresarUser                1006
#define EDT_User                        1007
#define EDT_NombreUser                  1009
#define EDT_ContraUser                  1010
#define EDT_VeriContraUser              1011
#define IDB_Especialidades              1012
#define IDB_RegistroMedico              1013
#define IDB_RegistroCitas               1014
#define IDB_Pacientes                   1015
#define IDB_ConsultaCitas               1016
#define LB_Especialidades               1017
#define IDB_AltaEspecialidad            1018
#define IDB_BajaEspecialidad            1019
#define IDB_CambiarEspecialidad         1020
#define EDT_NombreEspecialidad          1021
#define EDT_DescripcionDeEspecialidad   1022
#define IDB_GuardarEspecialidad         1023
#define IDB_RegresarEspecialidad        1024
#define IDB_GuardarEdicionEspecialidad  1025
#define IDB_RegresarEdicionEspecialidad 1026
#define EDT_EspecialidadEdicion         1027
#define EDT_DescripcionEdiconEspecialidad 1028
#define IDB_RegresarEspecialidades      1029
#define EDT_NombreDoctor                1030
#define EDT_CedulaRegistro              1031
#define EDT_ApellidoPDoctor             1032
#define EDT_NumeroDoctorRegistro        1033
#define EDT_ApellidoMDoctor             1034
#define EDT_NumeroConsultorioRegistro   1035
#define DTP_HoraIncioTrabajo            1036
#define DTP_HoraFInalTrabajo            1037
#define RB_Lunes                        1038
#define RB_Martes                       1039
#define RB_Miercoles                    1040
#define RB_Jueves                       1041
#define RB_Viernes                      1042
#define RB_Sabado                       1043
#define RB_Domingo                      1044
#define PC_FotoDoctor                   1045
#define BTN_CargarFoto                  1046
#define BTN_GuardarInfoDoctor           1048
#define BTN_RegresarRegistro            1050
#define EDT_NombrePaciente              1051
#define RB_HombreRegistro               1053
#define RB_MujerRegistro                1054
#define EDT_NumeroPaciente              1055
#define EDT_Refencia                    1056
#define DTP_NacimientoPaciente          1057
#define EDT_EdadPacientes               1058
#define BTN_GuardarPacientes            1060
#define BTN_RegresarPacientes           1061
#define EDT_ApellidoPaternoPaciente     1062
#define EDT_ApellidoMaternoPaciente     1063
#define EDT_PrimerDoctorPacientes       1064
#define CB_Pacientes                    1066
#define CB_Medicos                      1067
#define CB_Especialidad                 1068
#define DTP_DiaDeCita                   1070
#define DTP_HoraDeCita                  1071
#define BTN_GuardarCita                 1072
#define BTN_RegresarGuardar             1073
#define PC_DoctorConsulta               1074
#define ST_PacienteCita                 1075
#define ST_DoctorCita                   1076
#define ST_EspecialidadCita             1077
#define ST_NumeroTelefonicoCita         1078
#define ST_HoraInicio                   1079
#define ST_HoraFinal                    1080
#define BTN_OkCita                      1081
#define ST_FechaCompletaCita            1082
#define LB_Citas                        1083
#define BTN_MedicoCitas                 1084
#define BTN_SemanaCitas                 1085
#define BTN_EspecialidadCitas           1086
#define BTN_CompletadoCita              1087
#define BTN_CancelarCita                1088
#define BTN_RegresarCitas               1089
#define BTN_ConfirmarCancelacion        1090
#define BTN_RegresarCancelacion         1091
#define EDT_Cancelacion                 1092
#define BTN_ContinuarMedicoCitas        1093
#define BTN_regresarconsultacitasmedico 1094
#define EDT_BuscadorMedicosCitas        1095
#define EDT_NumeroDeMesCita             1096
#define LB_CitasMedico                  1097
#define BTN_OkMedico                    1098
#define BTN_BuscarSemanaCita            1099
#define EDT_NumeroDeSemanaCita          1100
#define BTN_RegresarSemanaCita          1102
#define BTN_BuscadorEspecialidad        1103
#define BTN_regresarbuscadorespecialidad 1104
#define EDT_buscadorEspecialidad        1105
#define EDT_buscadorSemanaEspecialidad  1106
#define CB_especialidadMdico            1107
#define EDT_HoraEntradaMedico           1108
#define EDT_HoraSalidaMedico            1109
#define BTN_MostrarPacientes            1109
#define BTN_MostrarMedicos              1110
#define LB_AllPacientes                 1111
#define BTN_CambiarPaciente             1112
#define BTN_EliminarPaciente            1113
#define BTN_regresarTPacientes          1114
#define EDT_NombreEdicionPacieente      1115
#define EDT_ApellidoPEP                 1117
#define EDT_ApellidoMEP                 1118
#define EDT_NumeroTelefoniocoEP         1120
#define BTN_GuardarEdicion              1121
#define BTN_RegresarEdicionP            1122
#define LB_allMedicos                   1123
#define BTN_EliminarMedico              1124
#define EDT_cedulabuscarmedico          1125
#define BTN_editarMedico                1126
#define BTN_regresarmostrarMedico       1127
#define EDT_EditarNombreMedico          1128
#define EDT_EditarApellidoPMedico       1129
#define EDT_ApellidoMMedico             1131
#define EDT_numeroTEdicionMedico        1132
#define BTN_guardarEdiconMedico         1134
#define BTN_regresarEdicionMedico       1135
#define BTN_EditarCita                  1137
#define IDC_COMBO1                      1138

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1139
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
